//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Apellido { get; set; }
        public Nullable<System.DateTime> Fecha_de_nacimiento { get; set; }
        public string Genero { get; set; }
        public string Direccion { get; set; }
        public string Estado_Civil { get; set; }
        public string Movil { get; set; }
        public string Telefono { get; set; }
        public string Correo_Electronico { get; set; }
    }
}
